### ISSUE TITLE
m_b_corr_err_DIAG and the covariance matrix?

### ISSUE THREAD

**Issue by komatsu5147** [PantheonPlusSH0ES/DataRelease#6]
This is probably a stupid question. `m_b_corr_err_DIAG` in `Pantheon+SH0ES.dat` is "determined from the diagonal of the covariance matrix", according to the description.

However, the square-root of the diagonal elements of `Pantheon+SH0ES_STAT+SYS.cov` is about 70% of `m_b_corr_err_DIAG`. What is the relationship between these two values? Thanks for your help!

**Comment by djbrout** [comment]
This is the statistical component only. 
To be clear this column should just be used for plotting, and not for cosmological fits.

**Comment by komatsu5147** [comment]
Thank you for your reply!

Yes, I understand that one must use the covariance. My question is how ``m_b_corr_err_DIAG`` is related to ``Pantheon+SH0ES_STAT+SYS.cov``, whose square-root is **smaller** than ``m_b_corr_err_DIAG``. If I used ``Pantheon+SH0ES_STATONLY.cov`` instead, the discrepancy is worse because the diagonal elements of the latter is smaller than the former.

In other words, I would like to know how "``m_b_corr_err_DIAG`` is determined from the diagonal of the covariance matrix" as written in the file.

**Comment by djbrout** [comment]
ah, sorry i forgot to mention that the diagonal errors reported do not include the cepheid distance covariance while the systematic covariance does include the cepheid uncertainties systematics (for measuring H0).

**Comment by komatsu5147** [comment]
Right, but the puzzling thing is that the diagonal elements of both covariance matrices (both ``STATONLY`` and ``STAT+SYS``) are  _smaller_ (about 70%) than the diagonal errors reported in ``m_b_corr_err_DIAG``...

**Comment by komatsu5147** [comment]
Here is a plot showing the ratio of the diagonal elements of ``Pantheon+SH0ES_STATONLY.cov`` to ``m_b_corr_err_DIAG`` for all Pantheon+SH0ES samples. It's about 0.7 on average. 

![plot](https://user-images.githubusercontent.com/51155988/212865643-2fe06bee-a750-4500-8827-0b3be9ecc536.png)

**Comment by komatsu5147** [comment]
Note: the y-axis shows the **square-root** of diag(covariance).

**Comment by aaordenes** [comment]
Good afternoon, I'm not sure if the question has already been answered (if it has, I would appreciate it if you could point me to it, please), but as KOMATSU5147 mentioned, could you help me clarify how to obtain "m_b_corr_err_DIAG" from the diagonal of the covariance matrix?"

**Comment by franciscotln** [comment]
Me too, same doubt 🤔 in the article **_The Pantheon+ Analysis: Cosmological Constraints_** there's a note about that but I cannot derive those values either.
<img width="442" alt="7" src="https://github.com/PantheonPlusSH0ES/DataRelease/assets/14295014/0a6f872d-5a04-4d9c-9b30-6de77f30689b">
