### ISSUE TITLE
Does the simulation provide biasCor_x1 and biasCor_c values?

### ISSUE THREAD

**Issue by CassiaNascimento** [PantheonPlusSH0ES/DataRelease#8]
Hello!

Comparing the parameters reported in the folder "DataReleasePantheon+_Data/4_DISTANCES_AND_COVAR" with previous .FITRES from Pantheon, I was wondering if there are no values for biasCor_mu, biasCor_x1 and biasCor_c from the simulations.

Thanks and best regards, 
Cássia

**Comment by djbrout** [comment]
Hi there. biascor_x1 and biascor_c are not provided because in Popovic+22
the methodology was converted to apply only Biascor MU (which is now called
"m_b_corr").

**Comment by CassiaNascimento** [comment]
OK! Thank you for your reply!
